const ADD_CONNECTION = 'ADD_CONNECTION'
const ADD_MULTIPLE_CONNECTIONS = 'ADD_MULTIPLE_CONNECTIONS'
const DELETE_CONNECTION = 'DELETE_CONNECTION'

const types = {
    ADD_CONNECTION,
    ADD_MULTIPLE_CONNECTIONS,
    DELETE_CONNECTION,
}

export default types;