const ADD_MUSICIAN = 'ADD_MUSICIAN'
const ADD_MULTIPLE_MUSICIANS = 'ADD_MULTIPLE_MUSICIANS'
const DELETE_MUSICIAN = 'DELETE_MUSICIAN'
const EDIT_MUSICIAN = 'EDIT_MUSICIAN'
const SET_MUSICIANS_SORTING = 'SET_MUSICIANS_SORTING'

const types = {
    ADD_MUSICIAN,
    ADD_MULTIPLE_MUSICIANS,
    DELETE_MUSICIAN,
    EDIT_MUSICIAN,
    SET_MUSICIANS_SORTING
}

export default types;